// data.js — placeholder pieces, clients, materials.
// Plain JS object on window for the Babel-compiled scripts to read.

window.FILIGREE_DATA = {
  pieces: [
    {
      id: "p-042",
      client: "Anna",
      title: "Anna's pendant",
      status: "in-process",
      stone: "Moonstone",
      stoneSize: "8 mm cabochon",
      stoneNote: "from her grandmother's collection — slightly clouded, the cloud is the whole point",
      wire: "Sterling, 18 ga",
      setting: "Twisted spiral bezel, six wire crown",
      held: "since the spring",
      price: 1420,
      progress: 0.62,
      dream: "Something that catches light the way the river did the morning we scattered her ashes.",
      letters: 4,
      lastTouched: "this morning",
    },
    {
      id: "p-040",
      client: "Jonah",
      title: "Jonah's ring",
      status: "finished",
      stone: "Amethyst",
      stoneSize: "6×4 mm faceted",
      wire: "14k gold-fill, 20 ga",
      setting: "Tension-wrapped spiral",
      held: "delivered in the spring",
      price: 3240,
      progress: 1.0,
      dream: "A ring to mark the season I stopped being afraid.",
      letters: 9,
      lastTouched: "three weeks ago",
    },
    {
      id: "p-044",
      client: "Mira",
      title: "Mira's wedding bands",
      status: "in-process",
      stone: "None — twin bands",
      stoneSize: "—",
      wire: "Sterling, 16 ga · twisted",
      setting: "Two bands, one with a single spiral, one with three",
      held: "since last Sunday",
      price: 2180,
      progress: 0.20,
      dream: "Two rings that look like they grew from the same tree.",
      letters: 2,
      lastTouched: "yesterday",
    },
    {
      id: "p-043",
      client: "Theo",
      title: "Theo's pendant",
      status: "awaiting-reply",
      stone: "Labradorite",
      stoneSize: "10×8 mm oval",
      wire: "Sterling, 18 ga",
      setting: "Awaiting his choice of two sketches",
      held: "since the week before last",
      price: null,
      progress: 0.10,
      dream: "Something for my sister. She loves the sea before a storm.",
      letters: 3,
      lastTouched: "five days ago",
    },
    {
      id: "p-039",
      client: "Lena",
      title: "Lena's earrings",
      status: "laid-aside",
      stone: "Garnet (×2)",
      stoneSize: "4 mm round",
      wire: "Sterling, 22 ga",
      setting: "Drop spiral",
      held: "since the new year",
      price: null,
      progress: 0,
      dream: "Held quietly — she may return when she's ready.",
      letters: 1,
      lastTouched: "in the winter",
    },
  ],

  letters: {
    "p-042": [
      { from: "anna", when: "in the spring", body: "I'm not sure how to ask for this. My grandmother's moonstone has been in a drawer for fifteen years and I can finally bear to wear her now." },
      { from: "me",   when: "the next morning", body: "Send me the stone when you're ready. I'll hold it for a while before we begin — that's how I work." },
      { from: "anna", when: "the next week", body: "It arrived. Did you see the cloud in the center? My mother said it was a flaw. I think it's the whole thing." },
      { from: "me",   when: "that evening", body: "I see it. We'll set it so the cloud reads. I'm sketching a twisted wire bezel — five or six wires, depending on how the stone wants to sit." },
    ],
  },

  materials: {
    wire: [
      { metal: "Sterling silver", gauge: "16 ga", length: "2.4 m", note: "twisted, for bands" },
      { metal: "Sterling silver", gauge: "18 ga", length: "8.1 m", note: "primary bezel wire" },
      { metal: "Sterling silver", gauge: "20 ga", length: "4.7 m", note: "wraps & accents" },
      { metal: "Sterling silver", gauge: "22 ga", length: "6.3 m", note: "fine work" },
      { metal: "14k gold-fill",   gauge: "20 ga", length: "1.8 m", note: "running low" },
      { metal: "14k gold-fill",   gauge: "22 ga", length: "0.9 m", note: "reorder" },
    ],
    stones: [
      { name: "Moonstone",     size: "8 mm cab",   count: 2, note: "Anna's incl." },
      { name: "Amethyst",      size: "6×4 mm fac", count: 4 },
      { name: "Labradorite",   size: "10×8 mm",   count: 1, note: "Theo's" },
      { name: "Garnet",        size: "4 mm round", count: 6 },
      { name: "Smoky quartz",  size: "12×10 mm",  count: 2 },
      { name: "Rainbow moonstone", size: "6 mm cab", count: 3 },
    ],
  },
};
