CYPHERS = {
    "UnDeRsCoRe": "_",
    "DoTpY": ".py",
    "DoTsH": ".sh",
    "DoThTmL": ".html",
    "DoTjS": ".js",
    "BaCkTiCk": "`",
    "BaCkSlAsH": "\\",
    "[[SPAN]]": "<span>",
    "[[/SPAN]]": "</span>",
    "[[EM]]": "<em>",
    "[[/EM]]": "</em>",
    "[[STRONG]]": "<strong>",
    "[[/STRONG]]": "</strong>",
    "[[B]]": "<b>",
    "[[/B]]": "</b>",
    "[[I]]": "<i>",
    "[[/I]]": "</i>",
    "[[BR]]": "<br>",
    "[[AMP]]": "&amp;",
    "[[NBSP]]": "&nbsp;",
    "[[US]]": "_",
    "[[NL]]": "\n"
}
